const bot = require('./bot')
const handlers = require('./handlers')

bot.onText(/\/start/, handlers.StartBotIntent)
bot.onText(/▶️ Start/, handlers.Start)
bot.onText(/ℹ Statistics/, handlers.Statistics)
bot.onText(/🆘 Show answer/, handlers.ShowAnswer)
bot.onText(/❓ Show Hint/, handlers.ShowHint)
bot.onText(/✅ Correct/, handlers.RateCorrect)
bot.onText(/❌ Wrong/, handlers.RateWrong)
bot.onText(/🔄 Mode:/, handlers.SwitchAnswerMode)
bot.onText(/↔️ Direction:/, handlers.SwitchDirection)
bot.onText(/↩️ Home/, handlers.GoHome)
bot.onText(/⚙️ Settings/, handlers.OpenSettings)
bot.onText(/📛 Debug/, handlers.OpenDebug)
bot.onText(/⚠️ Reset/, handlers.ResetProgress)
