const bot = require('./bot')
const handlers = require('./handlers')

bot.onText(/\/start/, handlers.StartBotIntent)
bot.onText(/^▶️/, handlers.Start)
bot.onText(/^ℹ️/, handlers.Statistics)
bot.onText(/^❓/, handlers.ShowAnswer)
bot.onText(/^💡/, handlers.ShowHint)
bot.onText(/^✅/, handlers.RateCorrect)
bot.onText(/^❌/, handlers.RateWrong)
bot.onText(/^🔄/, handlers.SwitchAnswerMode)
bot.onText(/^↔️/, handlers.SwitchDirection)
bot.onText(/^↩️/, handlers.GoHome)
bot.onText(/^🔤/, handlers.SwitchLang)
bot.onText(/^⚙️/, handlers.OpenSettings)
bot.onText(/^📛/, handlers.OpenDebug)
bot.onText(/^⚠️/, handlers.ResetProgress)
bot.onText(/^🀄/, handlers.OpenGameMenu)
bot.onText(/^🔢/, handlers.SwitchGameMode)
